[tool.poetry]
name = "space-invaders"
version = "0.1.0"
description = ""
authors = ["Tomhausen <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pgzero = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
